"""Insert figure references into the manuals at verified anchor points."""
import pathlib, sys

D = pathlib.Path(__file__).resolve().parent.parent / "docs"

def img(name, caption, width="100%"):
    return f'\n\n![{caption}](docs/figures/{name}.png){{width={width}}}\n'

INSERTS = [
    ("labs/lab01/manual.md", "then confirm it against the system.",
     img("lab01_qos_matrix", "QoS compatibility, generated by calling `qos_rules.check`. The red cells produce no error message of any kind.", "78%")),
    ("labs/lab02/manual.md", "supplied unit tests does.",
     img("lab02_diff_drive", "The differential drive model. Course constants shown are the frozen values in `RobotSpec`.", "82%")),
    ("labs/lab03/manual.md", "twenty five centimetres between scans, which is not.",
     img("lab03_rate_diagnostics", "Three sensor streams, all averaging about 10 Hz. Statistics computed by `rate_stats.analyse`.", "95%")),
    ("labs/lab04/manual.md", "That is the entire algorithm.",
     img("lab04_log_odds", "Left: the log odds transformation. Right: why the clamp matters.", "95%")),
    ("labs/lab04/manual.md", "one line of code.",
     img("lab04_inverse_sensor_model", "One beam, two constants. Cells beyond the hit are left untouched.", "82%")),
    ("labs/lab04/manual.md", "Then restore the correct behaviour.",
     img("lab04_mapping_correct_vs_ring", "Both maps built by `occupancy.py` from the same run. The only difference is whether a return at the sensor limit is treated as a hit.", "100%")),
    ("labs/lab05/manual.md", "AMCL uses it, and so does the supplied",
     img("lab05_particle_convergence", "Global localisation with 600 particles and no initial pose estimate, produced by `particle_filter.py`.", "100%")),
    ("labs/lab06/manual.md", "includes an argument about this number.",
     img("lab06_inflation", "Inflation on a real arena, computed by `grid_tools.inflate`. Black is the obstacle, blue the inflated region.", "100%")),
    ("labs/lab07/manual.md", "node to a fallback is one line.",
     img("diagram_recovery_tree", "The recovery tree from Code 7.1. RoundRobin escalates rather than repeating the cheapest action.", "100%")),
    ("labs/lab09/manual.md", "observe before you run anything.",
     img("lab09_reward_arithmetic", "The freezing failure is predictable before training starts.", "78%")),
    ("labs/lab09/manual.md", "Your numbers will differ, because your seed differs. The pattern should not.",
     img("lab09_results", "Measured over 30 held-out arenas. The policy with the best safety metrics never reaches the goal.", "100%")),
    ("labs/lab10/manual.md", "That is a clue, and Exercise 10.3 follows it.",
     img("lab10_trajectories", "Classical and learned controllers on identical arenas. A star ends at the goal, a cross does not.", "100%")),
    ("projects/project2_specification.md", "reference robot.",
     img("arena_grammar_samples", "Four arenas drawn from the published grammar. Practice seeds 0 to 499 are released in week 9.", "100%")),
    ("projects/project2_specification.md", "then take an efficient route, then be quick.",
     img("project2_scoring", "Scores computed by `arc_eval/scoring.py` for six representative runs.", "95%")),
    ("proposal.md", "## 3. The ten week architecture",
     img("diagram_course_arc", "The semester arc.", "100%")),
]

REPLACEMENTS = [
    ("labs/lab06/manual.md", "```\n   /scan  /odom  /tf", "```\n",
     img("diagram_nav2_architecture", "The Nav2 stack. Dashed grey: the behaviour tree sequencing the servers. Dashed red: the collision monitor's independent sensor subscription.", "88%")),
    ("labs/lab08/manual.md", "```\n                     arc_rl/nav_core.py", "```\n",
     img("diagram_two_environments", "Two environments, one frozen contract. Throughput figures are measured on the course VM.", "100%")),
    ("labs/lab02/manual.md", "```\nmap --(AMCL, Lab 5)--> odom", "```\n",
     img("diagram_tf_tree", "The transform tree. Each edge has exactly one publisher.", "72%")),
]

# Two phase: validate EVERY edit against the current files and build the new
# content in memory, then write only if all of it checks out. The first version
# of this script wrote as it went and reported failures afterwards, so a partial
# run left some files edited; re-running then applied those edits a second time
# and produced duplicated figures. Validate first, write last.
def apply_all():
    pending, failures = {}, []

    def current(rel):
        return pending.get(rel, (D / rel).read_text())

    for rel, anchor, block in INSERTS:
        s = current(rel)
        if block.strip() in s:
            continue                                   # idempotent: already there
        n = s.count(anchor)
        if n != 1:
            failures.append(f"{rel}: anchor appears {n} times: {anchor[:52]!r}")
            continue
        i = s.index(anchor) + len(anchor)
        pending[rel] = s[:i] + block + s[i:]

    for rel, start_marker, end_marker, block in REPLACEMENTS:
        s = current(rel)
        if block.strip() in s:
            continue
        if s.count(start_marker) != 1:
            failures.append(f"{rel}: block start appears {s.count(start_marker)} times")
            continue
        i = s.index(start_marker)
        j = s.index(end_marker, i + len(start_marker)) + len(end_marker)
        pending[rel] = s[:i] + block.strip() + "\n" + s[j:]

    if failures:
        print("FAILED, nothing written:")
        for f in failures:
            print("  ", f)
        return 1

    for rel, text in pending.items():
        (D / rel).write_text(text)
    print(f"{len(pending)} file(s) updated; "
          f"{len(INSERTS)} figures and {len(REPLACEMENTS)} diagrams verified in place")
    return 0


sys.exit(apply_all())
