"""
Architecture diagrams and conceptual figures.

Block diagrams are rendered with Graphviz rather than drawn, so the structure
stays consistent across the manuals and can be edited as text. The conceptual
figures are generated by calling the same course modules students use, so the
QoS matrix, the inflation illustration and the rate diagnostics cannot drift away
from the code they describe.

    python3 scripts/make_diagrams.py
"""

from __future__ import annotations

import math
import subprocess
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle, FancyArrowPatch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts.make_figures import ACCENT, GOOD, GRID, INK, MUTED, PAPER, PRIMARY, OUT, save  # noqa: E402

FONT = "DejaVu Sans"


def render_dot(source: str, name: str, engine: str = "dot") -> None:
    path = OUT / f"{name}.png"
    subprocess.run([engine, "-Tpng", "-Gdpi=200", "-o", str(path)],
                   input=source, text=True, check=True)
    print(f"  docs/figures/{name}.png")


def node_style(fill=PAPER, colour=INK, shape="box"):
    return (f'shape={shape}, style="rounded,filled", fillcolor="{fill}", '
            f'color="{colour}", fontname="{FONT}", fontsize=10, '
            f'penwidth=1.2, margin="0.16,0.09"')


# ===========================================================================
# Architecture diagrams
# ===========================================================================

def diagram_nav2_architecture():
    render_dot(f'''
digraph nav2 {{
  rankdir=TB; bgcolor="{PAPER}"; splines=ortho; nodesep=0.35; ranksep=0.38;
  node [{node_style()}];
  edge [color="{INK}", fontname="{FONT}", fontsize=8, penwidth=1.1, arrowsize=0.7];

  subgraph cluster_in {{
    label="sensing"; fontname="{FONT}"; fontsize=9; fontcolor="{MUTED}";
    color="{GRID}"; style=rounded;
    scan [label="/scan", {node_style(fill="#eef3f8")}];
    odom [label="/odom", {node_style(fill="#eef3f8")}];
    mapf [label="saved map", {node_style(fill="#eef3f8")}];
  }}

  amcl   [label="AMCL\\nlocalisation", {node_style(fill="#dfeaf3")}];
  gcost  [label="global costmap\\nstatic + obstacle + inflation", {node_style(fill="#dfeaf3")}];
  lcost  [label="local costmap\\nrolling 5 x 5 m", {node_style(fill="#dfeaf3")}];
  plan   [label="planner_server\\nNavFn: Dijkstra or A*", {node_style(fill="#cfe0ee")}];
  ctrl   [label="controller_server\\nDWB or MPPI", {node_style(fill="#cfe0ee")}];
  smooth [label="velocity_smoother", {node_style()}];
  monitor[label="collision_monitor\\nlast line of defence", {node_style(fill="#f6e2dc", colour=ACCENT)}];
  diff   [label="diff_drive_controller", {node_style()}];
  robot  [label="robot", {node_style(fill="#e3efe7", colour=GOOD)}];
  bt     [label="bt_navigator\\nbehaviour tree", {node_style(fill="#f4efe3")}];

  mapf -> gcost; scan -> gcost; scan -> lcost; scan -> amcl; odom -> amcl;
  amcl -> gcost [label=" map to odom"];
  gcost -> plan; plan -> ctrl [label=" nav_msgs/Path"]; lcost -> ctrl;
  ctrl -> smooth [label=" cmd_vel"]; smooth -> monitor; monitor -> diff; diff -> robot;
  bt -> plan [style=dashed, color="{MUTED}"];
  bt -> ctrl [style=dashed, color="{MUTED}", label=" sequences\\n and recovers"];
  scan -> monitor [style=dashed, color="{ACCENT}", label=" independent"];
}}
''', "diagram_nav2_architecture")


def diagram_two_environments():
    render_dot(f'''
digraph twoenv {{
  rankdir=LR; bgcolor="{PAPER}"; nodesep=0.3; ranksep=0.5;
  node [{node_style()}];
  edge [color="{INK}", fontname="{FONT}", fontsize=8, penwidth=1.1, arrowsize=0.7];

  contract [label="arc_rl/nav_core.py\\nRobotSpec | ObsSpec\\nbuild_observation() | scale_action()",
            {node_style(fill="#f4efe3")}];

  subgraph cluster_train {{
    label="TRAINING"; fontname="{FONT}"; fontsize=9; fontcolor="{PRIMARY}";
    color="{GRID}"; style=rounded;
    fast [label="FastNavEnv\\npure NumPy, no ROS\\n~3,800 steps/s", {node_style(fill="#dfeaf3")}];
    ppo  [label="PPO\\n200k steps in 1.9 min", {node_style(fill="#cfe0ee")}];
  }}

  subgraph cluster_eval {{
    label="EVALUATION AND DEPLOYMENT"; fontname="{FONT}"; fontsize=9; fontcolor="{GOOD}";
    color="{GRID}"; style=rounded;
    ros  [label="RosNavEnv\\nrclpy + Gazebo\\n~20 steps/s", {node_style(fill="#e3efe7")}];
    gz   [label="Gazebo Harmonic", {node_style()}];
  }}

  contract -> fast [label=" same 29 values"];
  contract -> ros  [label=" same 29 values"];
  fast -> ppo [dir=both];
  ppo -> ros [label=" the trained policy\\n loads unchanged", style=bold, color="{ACCENT}"];
  ros -> gz [dir=both];
}}
''', "diagram_two_environments")


def diagram_tf_tree():
    render_dot(f'''
digraph tf {{
  rankdir=TB; bgcolor="{PAPER}"; nodesep=0.22; ranksep=0.32;
  node [{node_style()}];
  edge [color="{INK}", fontname="{FONT}", fontsize=8, penwidth=1.1, arrowsize=0.7];

  map  [label="map", {node_style(fill="#dfeaf3")}];
  odom [label="odom", {node_style(fill="#dfeaf3")}];
  foot [label="base_footprint", {node_style(fill="#cfe0ee")}];
  base [label="base_link", {node_style(fill="#cfe0ee")}];
  laser [label="laser_link"]; imu [label="imu_link"];
  lw [label="left_wheel_link"]; rw [label="right_wheel_link"];

  map -> odom [label=" AMCL\\n correct, jumps", fontcolor="{ACCENT}"];
  odom -> foot [label=" diff_drive_controller\\n smooth, drifts", fontcolor="{PRIMARY}"];
  foot -> base [label=" fixed"];
  base -> laser [label=" fixed"]; base -> imu [label=" fixed"];
  base -> lw [label=" continuous"]; base -> rw [label=" continuous"];
  {{rank=same; laser; imu; lw; rw;}}
}}
''', "diagram_tf_tree")


def diagram_recovery_tree():
    render_dot(f'''
digraph bt {{
  rankdir=TB; bgcolor="{PAPER}"; nodesep=0.28; ranksep=0.34;
  node [{node_style()}];
  edge [color="{INK}", penwidth=1.1, arrowsize=0.7];

  root [label="RecoveryNode\\nretries = 6", {node_style(fill="#f4efe3")}];
  pipe [label="PipelineSequence\\nnavigate with replanning", {node_style(fill="#dfeaf3")}];
  plan [label="ComputePathToPose\\nrate limited to 1 Hz"];
  foll [label="FollowPath"];
  fb   [label="ReactiveFallback\\nrecovery", {node_style(fill="#f6e2dc", colour=ACCENT)}];
  upd  [label="GoalUpdated?\\nabandon recovery", {node_style(fill="#f6e2dc")}];
  rr   [label="RoundRobin\\nescalates, does not repeat", {node_style(fill="#f6e2dc")}];
  c1 [label="1. clear costmaps\\nfree, fixes stale obstacles"];
  c2 [label="2. spin\\nrefreshes the view"];
  c3 [label="3. wait\\nfor dynamic obstacles"];
  c4 [label="4. back up\\nfirst action that can hurt"];

  root -> pipe; root -> fb;
  pipe -> plan; pipe -> foll;
  fb -> upd; fb -> rr;
  rr -> c1; rr -> c2; rr -> c3; rr -> c4;
  {{rank=same; c1; c2; c3; c4;}}
}}
''', "diagram_recovery_tree")


def diagram_course_arc():
    """The ten week arc, for the proposal and the design baseline."""
    stages = [
        ("1-3", "ROS 2, robot\nmodel, sensors", PRIMARY),
        ("4-5", "mapping and\nlocalisation", PRIMARY),
        ("P1", "Project 1", GOOD),
        ("6-7", "Nav2 and\nrobust autonomy", PRIMARY),
        ("8-9", "RL environment\nand training", ACCENT),
        ("10", "hybrid and\nsim-to-real", ACCENT),
        ("P2", "Grand\nChallenge", GOOD),
    ]
    fig, ax = plt.subplots(figsize=(10.0, 1.9))
    x = 0.0
    for i, (week, label, colour) in enumerate(stages):
        width = 1.5 if week in ("P1", "P2") else 2.0
        ax.add_patch(plt.Rectangle((x, 0.25), width, 0.9, facecolor=colour,
                                   alpha=0.16, edgecolor=colour, lw=1.6,
                                   joinstyle="round"))
        ax.text(x + width / 2, 0.92, week, ha="center", fontsize=9.5,
                weight="bold", color=colour)
        ax.text(x + width / 2, 0.55, label, ha="center", va="center",
                fontsize=8.5, color=INK)
        if i < len(stages) - 1:
            ax.annotate("", xy=(x + width + 0.28, 0.7), xytext=(x + width + 0.02, 0.7),
                        arrowprops=dict(arrowstyle="-|>", color=MUTED, lw=1.4))
        x += width + 0.3
    ax.text(x / 2, 0.02, "implement the concept, configure the production system, "
                         "measure both", ha="center", fontsize=8.5, color=MUTED,
            style="italic")
    ax.set_xlim(-0.2, x); ax.set_ylim(-0.05, 1.3)
    ax.axis("off")
    save(fig, "diagram_course_arc")


# ===========================================================================
# Conceptual figures generated from the course modules
# ===========================================================================

def fig_lab01_qos_matrix():
    """Generated by calling qos_rules.check, so it cannot contradict the code."""
    from starters.lab01.qos_rules import QoS, check

    offers = [("BEST_EFFORT\nVOLATILE", QoS("best_effort", "volatile")),
              ("RELIABLE\nVOLATILE", QoS("reliable", "volatile")),
              ("RELIABLE\nTRANSIENT_LOCAL", QoS("reliable", "transient_local"))]
    requests = offers

    grid = np.zeros((len(requests), len(offers)))
    for i, (_, sub) in enumerate(requests):
        for j, (_, pub) in enumerate(offers):
            grid[i, j] = 1.0 if check(pub, sub)[0] else 0.0

    fig, ax = plt.subplots(figsize=(5.6, 3.4))
    ax.imshow(grid, cmap=matplotlib.colors.ListedColormap(["#f6e2dc", "#e3efe7"]),
              vmin=0, vmax=1)
    for i in range(len(requests)):
        for j in range(len(offers)):
            ok = grid[i, j] > 0.5
            ax.text(j, i, "receives\nmessages" if ok else "SILENT\nno error",
                    ha="center", va="center", fontsize=8,
                    color=GOOD if ok else ACCENT, weight="bold")
    ax.set_xticks(range(len(offers)), [o[0] for o in offers], fontsize=8)
    ax.set_yticks(range(len(requests)), [r[0] for r in requests], fontsize=8)
    ax.set_xlabel("publisher OFFERS", fontsize=9)
    ax.set_ylabel("subscriber REQUESTS", fontsize=9)
    ax.set_title("QoS compatibility: a mismatch raises nothing at all")
    ax.grid(False)
    save(fig, "lab01_qos_matrix")


def fig_lab02_diff_drive():
    fig, ax = plt.subplots(figsize=(6.0, 3.4))
    L, r = 3.0, 0.75
    ax.add_patch(plt.Rectangle((-1.6, -L / 2), 3.2, L, facecolor="#dfeaf3",
                               edgecolor=INK, lw=1.4, zorder=1))
    for sign, name in ((1, r"$\omega_L$"), (-1, r"$\omega_R$")):
        y = sign * L / 2
        ax.add_patch(plt.Rectangle((-0.9, y - 0.22), 1.8, 0.44, facecolor=INK,
                                   edgecolor=INK, zorder=3))
        ax.annotate(name, (0.0, y + sign * 0.55), ha="center", fontsize=11, color=ACCENT)
    ax.annotate("", xy=(0, L / 2), xytext=(0, -L / 2),
                arrowprops=dict(arrowstyle="<|-|>", color=ACCENT, lw=1.3))
    ax.text(0.16, 0.0, "$L$ = 0.350 m", fontsize=9.5, color=ACCENT, va="center")
    ax.annotate("", xy=(3.1, 0), xytext=(0.2, 0),
                arrowprops=dict(arrowstyle="-|>", color=PRIMARY, lw=2.0))
    ax.text(3.25, 0.0, "$v$", fontsize=12, color=PRIMARY, va="center")
    ax.add_patch(matplotlib.patches.Arc((0, 0), 2.4, 2.4, theta1=25, theta2=115,
                                        color=GOOD, lw=2.0))
    ax.annotate("", xy=(-0.52, 1.09), xytext=(-0.3, 1.16),
                arrowprops=dict(arrowstyle="-|>", color=GOOD, lw=1.8))
    ax.text(-1.35, 1.35, r"$\omega$", fontsize=12, color=GOOD)
    ax.text(-1.6, -2.55,
            r"$v = \frac{r(\omega_R + \omega_L)}{2}$        "
            r"$\omega = \frac{r(\omega_R - \omega_L)}{L}$",
            fontsize=11, color=INK)
    ax.text(-1.6, -3.2, "wheel radius $r$ = 0.050 m", fontsize=8.5, color=MUTED)
    ax.set_xlim(-2.6, 4.4); ax.set_ylim(-3.5, 2.4)
    ax.set_aspect("equal"); ax.axis("off")
    ax.set_title("Differential drive: average gives translation, difference gives rotation")
    save(fig, "lab02_diff_drive")


def fig_lab03_rate_diagnostics():
    """Three streams that ros2 topic hz reports as roughly 10 Hz."""
    from starters.lab02.rate_stats import analyse

    healthy = [i / 10.0 for i in range(60)]
    jittery = [i / 10.0 + (0.028 if i % 2 else -0.028) for i in range(60)]
    stalled = [t + (0.75 if i > 30 else 0.0) for i, t in enumerate(healthy)]

    fig, axes = plt.subplots(3, 1, figsize=(7.6, 3.6), sharex=True)
    for ax, (stamps, name, colour) in zip(axes, [
            (healthy, "healthy", GOOD), (jittery, "jittery", PRIMARY),
            (stalled, "periodic stall", ACCENT)]):
        report = analyse(stamps, expected_hz=10.0)
        ax.vlines(stamps, 0, 1, color=colour, lw=1.1)
        ax.set_yticks([])
        ax.set_ylabel(name, rotation=0, ha="right", va="center", fontsize=8.5)
        ax.text(0.995, 0.62,
                f"hz reports {report.mean_hz:.1f} Hz   |   jitter {report.jitter_ms:.0f} ms   "
                f"|   worst gap {report.worst_gap_ms:.0f} ms   |   dropouts {report.dropouts}",
                transform=ax.transAxes, ha="right", fontsize=7.6,
                color=INK if report.healthy else ACCENT,
                weight="normal" if report.healthy else "bold")
        ax.grid(False)
        for side in ("top", "right", "left"):
            ax.spines[side].set_visible(False)
    axes[-1].set_xlabel("message timestamp (s)")
    fig.suptitle("All three average about 10 Hz. Only one is usable.",
                 fontsize=10, y=1.0, color=INK)
    save(fig, "lab03_rate_diagnostics")


def fig_lab06_inflation():
    """Real inflation, computed by grid_tools.inflate on a real arena."""
    from arc_rl.arenas import DEFAULT_GRAMMAR, rasterise, sample_scenario
    from starters.lab04.grid_tools import inflate

    scenario = sample_scenario(1002, DEFAULT_GRAMMAR)
    grid = rasterise(scenario, 0.05, 0.0)
    obstacles = grid.data

    fig, axes = plt.subplots(1, 3, figsize=(9.6, 3.3))
    for ax, radius_m, title in ((axes[0], 0.0, "raw obstacles"),
                                (axes[1], 0.25, "inflation 0.25 m"),
                                (axes[2], 0.90, "inflation 0.90 m")):
        cells = int(round(radius_m / 0.05))
        inflated = inflate(obstacles, cells)
        image = np.zeros(inflated.shape)
        image[inflated] = 1
        image[obstacles] = 2
        ax.imshow(image.T, origin="lower", vmin=0, vmax=2,
                  cmap=matplotlib.colors.ListedColormap([PAPER, "#b9cddc", INK]),
                  interpolation="nearest")
        ax.set_title(title, fontsize=9.5)
        ax.set_aspect("equal"); ax.grid(False); ax.set_xticks([]); ax.set_yticks([])
    axes[2].annotate("doorway now closed:\nno path exists", xy=(0.5, 0.5),
                     xycoords="axes fraction", xytext=(0.5, 1.12),
                     textcoords="axes fraction", ha="center", fontsize=8,
                     color=ACCENT, weight="bold")
    fig.suptitle("The inflation trade: too small and the robot clips corners, "
                 "too large and gaps it fits through disappear",
                 fontsize=9.5, y=1.04, color=INK)
    save(fig, "lab06_inflation")


DIAGRAMS = [
    diagram_nav2_architecture, diagram_two_environments, diagram_tf_tree,
    diagram_recovery_tree, diagram_course_arc,
    fig_lab01_qos_matrix, fig_lab02_diff_drive, fig_lab03_rate_diagnostics,
    fig_lab06_inflation,
]

if __name__ == "__main__":
    print("diagrams:")
    for fn in DIAGRAMS:
        fn()
